Make Camera Settings
argosdyne/ALES_QGC pull request #2
Opened 2024-05-24 05:12 UTC by Ubaydulloh99

Camera Settings component - done

![image](https://github.com/argosdyne/AELS_QGC/assets/132320777/cae94f88-a5a0-4307-ad1a-1cecb5c2d7a2)

2024-05-24 05:44 UTC, thanhkaist requested changes
Checkout the https://github.com/argosdyne/AELS_QGC/blob/master/CodingStyle.qml and update the naming convention

2024-05-24 05:44 UTC, thanhkaist commented on qgroundcontrol.qrc
> +        <file alias="QGroundControl/Controls/ToolStripHoverButton.qml">src/QmlControls/ToolStripHoverButton.qml</file>
shorten the alias

2024-05-24 05:44 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +    id: _root
remove _ do that id is root. This follows the naming convention

2024-05-24 05:44 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +        id: text1
rename the id to be move descriptive

2024-05-24 05:44 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +        font.pixelSize: 25
Using relative ScreenTools.defaultFontPixelHeight

2024-05-24 05:44 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +            id: toolSeparator1
No need id for this

2024-05-24 05:44 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +                font.pixelSize: 20
Using ScreenTools.defaultFontPixelHeight

2024-05-27 01:59 UTC, Ubaydulloh99 commented on qgroundcontrol.qrc
> +        <file alias="QGroundControl/Controls/ToolStripHoverButton.qml">src/QmlControls/ToolStripHoverButton.qml</file>
this ToolStripHoverButton row was already here, i cannot remove this line, only small open space was automatically entered i tried but it is not going away, it is staying there .i cannot delete this alias.

2024-05-27 04:17 UTC, thanhkaist reviewed
Could you consider to improve these suggestion

2024-05-27 04:17 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +
The rootWidth and rootHeight properties are declared but not bound to any values. Consider binding these properties to the actual screen dimensions or relevant parent dimensions.

property int rootWidth: Screen.width
property int rootHeight: Screen.height

2024-05-27 04:17 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +        anchors.top: text1.bottom
The anchors.top for the Column is set to text1.bottom, but text1 is undefined

2024-05-27 04:17 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +            id: itemDelegate1
The IDs for ItemDelegate and SwitchDelegate components are unique but redundant if not referenced elsewhere. Remove unused IDs to reduce clutter.

2024-05-27 04:17 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +            id: switchDelegate
The IDs for ItemDelegate and SwitchDelegate components are unique but redundant if not referenced elsewhere. Remove unused IDs to reduce clutter.

2024-05-27 04:17 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +            id: switchDelegate0
The IDs for ItemDelegate and SwitchDelegate components are unique but redundant if not referenced elsewhere. Remove unused IDs to reduce clutter.

2024-05-27 04:17 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +            id: switchDelegate1
The IDs for ItemDelegate and SwitchDelegate components are unique but redundant if not referenced elsewhere. Remove unused IDs to reduce clutter.

2024-05-27 04:17 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +            id: switchDelegate2
The IDs for ItemDelegate and SwitchDelegate components are unique but redundant if not referenced elsewhere. Remove unused IDs to reduce clutter.

2024-05-27 04:17 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +
You may miss to include screenTools

import QGroundControl.ScreenTools   1.0

2024-05-27 04:17 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +                color: "#ffffff"
Text color are all #ffffff. Could you consider using a centralized theme or constants for colors to maintain consistency and ease of updates.

2024-05-27 08:19 UTC, thanhkaist reviewed
Use property binding for the height

2024-05-27 08:19 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +            height: 40
Hardcoding. Please use property binding

2024-05-27 08:19 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +            height: 13
Hardcoding. Please use property binding

2024-05-27 08:19 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +            height: 40
Hardcoding. Please use property binding

2024-05-27 08:19 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +            height: 13
Hardcoding. Please use property binding

2024-05-27 08:19 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +            height: 52
Hardcoding. Please use property binding

2024-05-27 08:19 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +            height: 13
Hardcoding. Please use property binding

2024-05-27 08:19 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +            height: 52
Hardcoding. Please use property binding

2024-05-27 08:19 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +            height: 13
Hardcoding. Please use property binding

2024-05-27 08:19 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +            height: 52
Hardcoding. Please use property binding

2024-05-27 08:19 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +            height: 13
Hardcoding. Please use property binding

2024-05-27 08:19 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +            height: 52
Hardcoding. Please use property binding

2024-05-27 08:19 UTC, thanhkaist commented on src/QmlControls/CameraSettings.qml
> +            height: 52
Hardcoding. Please use property binding

2024-05-28 04:07 UTC, thanhkaist approved these changes

2024-05-28 04:10 UTC, merged